"""some minor fixes

Revision ID: 12f4403aac97
Revises: a2c99c522c88
Create Date: 2026-02-09 14:27:27.503555

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "12f4403aac97"
down_revision: Union[str, Sequence[str], None] = "a2c99c522c88"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("otps", sa.Column("email", sa.String(length=255), nullable=False))
    op.drop_column("refresh_tokens", "device_info")
    op.add_column("separated_audio_files", sa.Column("id", sa.UUID(), nullable=False))
    # op.create_foreign_key(
    #     op.f("fk_separated_audio_files__audio_files"),
    #     "separated_audio_files",
    #     "audio_files",
    #     ["id"],
    #     ["id"],
    #     ondelete="CASCADE",
    # )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(op.f('fk_separated_audio_files__audio_files'), 'separated_audio_files', type_='foreignkey')
    op.drop_column("separated_audio_files", "id")
    op.add_column(
        "refresh_tokens",
        sa.Column(
            "device_info", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("otps", "email")
    # ### end Alembic commands ###
