"""project 1-* analysis_records

Revision ID: 27b0de89d182
Revises: 626f0e064ec7
Create Date: 2026-02-23 18:46:51.295029

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "27b0de89d182"
down_revision: Union[str, Sequence[str], None] = "626f0e064ec7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_project_analysis_type", "analysis_records", ["project_id", "analysis_type"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_project_analysis_type", "analysis_records", type_="unique")
    # ### end Alembic commands ###
