"""audio no longer unique to project

Revision ID: 359a4b457a1c
Revises: f0503148a3c1
Create Date: 2026-05-17 19:05:13.054388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '359a4b457a1c'
down_revision: Union[str, Sequence[str], None] = 'f0503148a3c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_projects_main_audio_id'), 'projects', type_='unique')
    op.drop_constraint(op.f('separated_audio_files_parent_audio_id_fkey'), 'separated_audio_files', type_='foreignkey')
    op.drop_constraint(op.f('separated_audio_files_id_fkey'), 'separated_audio_files', type_='foreignkey')
    op.create_foreign_key(op.f('fk_separated_audio_files__id__audio_files'), 'separated_audio_files', 'audio_files', ['id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_separated_audio_files__parent_audio_id__audio_files'), 'separated_audio_files', 'audio_files', ['parent_audio_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_separated_audio_files__parent_audio_id__audio_files'), 'separated_audio_files', type_='foreignkey')
    op.drop_constraint(op.f('fk_separated_audio_files__id__audio_files'), 'separated_audio_files', type_='foreignkey')
    op.create_foreign_key(op.f('separated_audio_files_id_fkey'), 'separated_audio_files', 'audio_files', ['id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(op.f('separated_audio_files_parent_audio_id_fkey'), 'separated_audio_files', 'audio_files', ['parent_audio_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('uq_projects_main_audio_id'), 'projects', ['main_audio_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
