"""project - audio, seperatedaudio relationship

Revision ID: 363ff2019254
Revises: 8897be2b14cc
Create Date: 2026-02-15 20:51:44.339969

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "363ff2019254"
down_revision: Union[str, Sequence[str], None] = "8897be2b14cc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_audio_files_project_id"), table_name="audio_files")
    op.drop_constraint(
        op.f("fk_audio_files__projects"), "audio_files", type_="foreignkey"
    )
    op.drop_column("audio_files", "project_id")
    op.add_column("projects", sa.Column("main_audio_id", sa.UUID(), nullable=True))
    op.alter_column("projects", "user_id", existing_type=sa.UUID(), nullable=False)
    op.create_unique_constraint(
        op.f("uq_projects_main_audio_id"), "projects", ["main_audio_id"]
    )
    op.create_foreign_key(
        op.f("fk_projects__audio_files"),
        "projects",
        "audio_files",
        ["main_audio_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # op.create_foreign_key(op.f('fk_separated_audio_files__audio_files'), 'separated_audio_files', 'audio_files', ['id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(op.f('fk_separated_audio_files__audio_files'), 'separated_audio_files', type_='foreignkey')
    op.drop_constraint(op.f("fk_projects__audio_files"), "projects", type_="foreignkey")
    op.drop_constraint(op.f("uq_projects_main_audio_id"), "projects", type_="unique")
    op.alter_column("projects", "user_id", existing_type=sa.UUID(), nullable=True)
    op.drop_column("projects", "main_audio_id")
    op.add_column(
        "audio_files",
        sa.Column("project_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        op.f("fk_audio_files__projects"),
        "audio_files",
        "projects",
        ["project_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_index(
        op.f("ix_audio_files_project_id"), "audio_files", ["project_id"], unique=False
    )
    # ### end Alembic commands ###
