"""minor fixes

Revision ID: 3ac699e8c8d8
Revises: 363ff2019254
Create Date: 2026-02-16 09:24:33.207481

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3ac699e8c8d8"
down_revision: Union[str, Sequence[str], None] = "363ff2019254"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("audio_files_project_id_fkey"), "audio_files", type_="foreignkey"
    )
    op.add_column("projects", sa.Column("main_audio_id", sa.UUID(), nullable=True))
    op.drop_constraint(op.f("uq_projects_main_audio_id"), "projects", type_="unique")
    op.create_unique_constraint(
        op.f("uq_projects_main_audio_id"), "projects", ["main_audio_id"]
    )
    op.drop_constraint(op.f("projects_audio_id_fkey"), "projects", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_projects__audio_files"),
        "projects",
        "audio_files",
        ["main_audio_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_column("projects", "audio_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects", sa.Column("audio_id", sa.UUID(), autoincrement=False, nullable=True)
    )
    op.drop_constraint(op.f("fk_projects__audio_files"), "projects", type_="foreignkey")
    op.create_foreign_key(
        op.f("projects_audio_id_fkey"),
        "projects",
        "audio_files",
        ["audio_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_constraint(op.f("uq_projects_main_audio_id"), "projects", type_="unique")
    op.create_unique_constraint(
        op.f("uq_projects_main_audio_id"),
        "projects",
        ["audio_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("projects", "main_audio_id")
    op.create_foreign_key(
        op.f("audio_files_project_id_fkey"),
        "audio_files",
        "projects",
        ["project_id"],
        ["id"],
    )
    # ### end Alembic commands ###
