"""user: add is_verified prop

Revision ID: 59d66eab4878
Revises: f7e406039d4d
Create Date: 2026-02-05 21:03:32.379357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59d66eab4878'
down_revision: Union[str, Sequence[str], None] = 'f7e406039d4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_analysis_records_id'), 'analysis_records', ['id'])
    op.create_unique_constraint(op.f('uq_audio_features_id'), 'audio_features', ['id'])
    op.create_unique_constraint(op.f('uq_audio_files_id'), 'audio_files', ['id'])
    op.create_unique_constraint(op.f('uq_logs_id'), 'logs', ['id'])
    op.create_unique_constraint(op.f('uq_models_id'), 'models', ['id'])
    op.create_unique_constraint(op.f('uq_otps_id'), 'otps', ['id'])
    op.create_unique_constraint(op.f('uq_projects_id'), 'projects', ['id'])
    op.create_unique_constraint(op.f('uq_refresh_tokens_id'), 'refresh_tokens', ['id'])
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=False))
    op.create_unique_constraint(op.f('uq_users_id'), 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_id'), 'users', type_='unique')
    op.drop_column('users', 'email_verified')
    op.drop_constraint(op.f('uq_refresh_tokens_id'), 'refresh_tokens', type_='unique')
    op.drop_constraint(op.f('uq_projects_id'), 'projects', type_='unique')
    op.drop_constraint(op.f('uq_otps_id'), 'otps', type_='unique')
    op.drop_constraint(op.f('uq_models_id'), 'models', type_='unique')
    op.drop_constraint(op.f('uq_logs_id'), 'logs', type_='unique')
    op.drop_constraint(op.f('uq_audio_files_id'), 'audio_files', type_='unique')
    op.drop_constraint(op.f('uq_audio_features_id'), 'audio_features', type_='unique')
    op.drop_constraint(op.f('uq_analysis_records_id'), 'analysis_records', type_='unique')
    # ### end Alembic commands ###
