"""projectId index

Revision ID: 5a61c97c8f47
Revises: 27b0de89d182
Create Date: 2026-04-07 21:20:59.331392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5a61c97c8f47'
down_revision: Union[str, Sequence[str], None] = '27b0de89d182'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('feature_analysis_records', 'feature_vector',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.create_index('idx_project_user_id', 'projects', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_project_user_id', table_name='projects')
    op.alter_column('feature_analysis_records', 'feature_vector',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    # ### end Alembic commands ###
