"""relationship mismatch fix

Revision ID: 8897be2b14cc
Revises: 12f4403aac97
Create Date: 2026-02-09 21:10:19.530173

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8897be2b14cc"
down_revision: Union[str, Sequence[str], None] = "12f4403aac97"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_analysis_records_user_id"), table_name="analysis_records")
    op.drop_constraint(
        op.f("fk_analysis_records__users"), "analysis_records", type_="foreignkey"
    )
    op.drop_column("analysis_records", "user_id")
    op.drop_index(op.f("ix_audio_files_user_id"), table_name="audio_files")
    op.drop_constraint(op.f("fk_audio_files__users"), "audio_files", type_="foreignkey")
    op.drop_column("audio_files", "user_id")
    op.add_column(
        "separated_audio_files",
        sa.Column("separation_analysis_id", sa.UUID(), nullable=True),
    )
    op.create_index(
        op.f("ix_separated_audio_files_separation_analysis_id"),
        "separated_audio_files",
        ["separation_analysis_id"],
        unique=False,
    )
    # op.create_foreign_key(op.f('fk_separated_audio_files__audio_files'), 'separated_audio_files', 'audio_files', ['id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(
        op.f("fk_separated_audio_files__separation_analysis_records"),
        "separated_audio_files",
        "separation_analysis_records",
        ["separation_analysis_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_separated_audio_files__separation_analysis_records"),
        "separated_audio_files",
        type_="foreignkey",
    )
    # op.drop_constraint(op.f('fk_separated_audio_files__audio_files'), 'separated_audio_files', type_='foreignkey')
    op.drop_index(
        op.f("ix_separated_audio_files_separation_analysis_id"),
        table_name="separated_audio_files",
    )
    op.drop_column("separated_audio_files", "separation_analysis_id")
    op.add_column(
        "audio_files",
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        op.f("fk_audio_files__users"),
        "audio_files",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_index(
        op.f("ix_audio_files_user_id"), "audio_files", ["user_id"], unique=False
    )
    op.add_column(
        "analysis_records",
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        op.f("fk_analysis_records__users"),
        "analysis_records",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_index(
        op.f("ix_analysis_records_user_id"),
        "analysis_records",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###
