"""added file size prop => audio_file

Revision ID: 9d41e3193304
Revises: 5a61c97c8f47
Create Date: 2026-04-08 19:58:47.489614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d41e3193304'
down_revision: Union[str, Sequence[str], None] = '5a61c97c8f47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audio_files', sa.Column('file_size', sa.BigInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audio_files', 'file_size')
    # ### end Alembic commands ###
