"""refresh_token: add user agent metadata

Revision ID: a2c99c522c88
Revises: 59d66eab4878
Create Date: 2026-02-07 16:20:09.909724

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a2c99c522c88"
down_revision: Union[str, Sequence[str], None] = "59d66eab4878"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "refresh_tokens", sa.Column("device_info", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "refresh_tokens", sa.Column("ip_address", sa.String(length=64), nullable=True)
    )
    op.add_column(
        "refresh_tokens", sa.Column("user_agent", sa.String(length=512), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("refresh_tokens", "user_agent")
    op.drop_column("refresh_tokens", "ip_address")
    op.drop_column("refresh_tokens", "device_info")
    # ### end Alembic commands ###
