"""summary text type change from text to json

Revision ID: bf01dc499855
Revises: 359a4b457a1c
Create Date: 2026-05-20 19:04:35.750171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf01dc499855'
down_revision: Union[str, Sequence[str], None] = '359a4b457a1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_records', sa.Column('summary', sa.JSON(), nullable=True))
    op.drop_column('analysis_records', 'summary_text')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_records', sa.Column('summary_text', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('analysis_records', 'summary')
    # ### end Alembic commands ###
