"""create musimo schema

Revision ID: de909992388f
Revises: ce36d80651df
Create Date: 2026-01-24 20:16:21.493266

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "de909992388f"
down_revision: Union[str, Sequence[str], None] = "ce36d80651df"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "models",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "EMOTION", "INSTRUMENT", "FEATURES", "SEPARATION", name="analysistype"
            ),
            nullable=False,
        ),
        sa.Column("version", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("checkpoint_path", sa.String(length=500), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_models")),
        sa.UniqueConstraint("id", name=op.f("uq_models_id")),
    )
    op.create_table(
        "audio_files",
        sa.Column("file_path", sa.String(length=500), nullable=False),
        sa.Column("duration", sa.Float(), nullable=True),
        sa.Column("sample_rate", sa.Integer(), nullable=True),
        sa.Column(
            "source_type",
            sa.Enum(
                "ORIGINAL", "VOCALS", "DRUMS", "BASS", "OTHER", name="audiosourcetype"
            ),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("checksum", sa.String(length=128), nullable=False),
        sa.Column("channels", sa.Integer(), nullable=False),
        sa.Column(
            "format",
            sa.Enum("WAV", "MP3", "FLAC", "AAC", "OGG", name="audioformat"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_audio_files_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audio_files")),
        sa.UniqueConstraint("checksum", name=op.f("uq_audio_files_checksum")),
        sa.UniqueConstraint("id", name=op.f("uq_audio_files_id")),
    )
    op.create_index(
        op.f("ix_audio_files_user_id"), "audio_files", ["user_id"], unique=False
    )
    op.create_table(
        "projects",
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_projects_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
        sa.UniqueConstraint("id", name=op.f("uq_projects_id")),
    )
    op.create_index(op.f("ix_projects_user_id"), "projects", ["user_id"], unique=False)
    op.create_table(
        "analysis_jobs",
        sa.Column("audio_id", sa.UUID(), nullable=False),
        sa.Column("model_id", sa.UUID(), nullable=True),
        sa.Column(
            "analysis_type",
            sa.Enum(
                "EMOTION", "INSTRUMENT", "FEATURES", "SEPARATION", name="analysistype"
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("QUEUED", "PROCESSING", "COMPLETED", "FAILED", name="jobstatus"),
            nullable=False,
        ),
        sa.Column("log", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["audio_id"],
            ["audio_files.id"],
            name=op.f("fk_analysis_jobs_audio_id_audio_files"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["models.id"],
            name=op.f("fk_analysis_jobs_model_id_models"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_analysis_jobs_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_analysis_jobs")),
        sa.UniqueConstraint("id", name=op.f("uq_analysis_jobs_id")),
    )
    op.create_index(
        op.f("ix_analysis_jobs_audio_id"), "analysis_jobs", ["audio_id"], unique=False
    )
    op.create_index(
        op.f("ix_analysis_jobs_user_id"), "analysis_jobs", ["user_id"], unique=False
    )
    op.create_table(
        "audio_features",
        sa.Column("audio_id", sa.UUID(), nullable=False),
        sa.Column(
            "feature_type",
            sa.Enum(
                "LOW_LEVEL",
                "MID_LEVEL",
                "HIGH_LEVEL",
                "EMBEDDINGS",
                "MEL_SPECTROGRAM",
                name="featuretype",
            ),
            nullable=False,
        ),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["audio_id"],
            ["audio_files.id"],
            name=op.f("fk_audio_features_audio_id_audio_files"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audio_features")),
        sa.UniqueConstraint("id", name=op.f("uq_audio_features_id")),
    )
    op.create_index(
        op.f("ix_audio_features_audio_id"), "audio_features", ["audio_id"], unique=False
    )
    op.create_table(
        "logs",
        sa.Column("audio_id", sa.UUID(), nullable=True),
        sa.Column("entity_type", sa.String(length=50), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("log_level", sa.String(length=20), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["audio_id"],
            ["audio_files.id"],
            name=op.f("fk_logs_audio_id_audio_files"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_logs")),
        sa.UniqueConstraint("id", name=op.f("uq_logs_id")),
    )
    op.create_table(
        "separated_sources",
        sa.Column("parent_audio_id", sa.UUID(), nullable=False),
        sa.Column(
            "source_type",
            sa.Enum(
                "ORIGINAL", "VOCALS", "DRUMS", "BASS", "OTHER", name="audiosourcetype"
            ),
            nullable=False,
        ),
        sa.Column("file_path", sa.String(length=500), nullable=False),
        sa.Column("duration", sa.Float(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["parent_audio_id"],
            ["audio_files.id"],
            name=op.f("fk_separated_sources_parent_audio_id_audio_files"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_separated_sources")),
        sa.UniqueConstraint("id", name=op.f("uq_separated_sources_id")),
    )
    op.create_index(
        op.f("ix_separated_sources_parent_audio_id"),
        "separated_sources",
        ["parent_audio_id"],
        unique=False,
    )
    op.create_table(
        "analysis_results",
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("results", sa.JSON(), nullable=False),
        sa.Column("summary_text", sa.Text(), nullable=True),
        sa.Column("visualization_paths", sa.JSON(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["analysis_jobs.id"],
            name=op.f("fk_analysis_results_job_id_analysis_jobs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_analysis_results")),
        sa.UniqueConstraint("id", name=op.f("uq_analysis_results_id")),
        sa.UniqueConstraint("job_id", name=op.f("uq_analysis_results_job_id")),
    )
    op.add_column("users", sa.Column("password_hash", sa.String(), nullable=False))
    op.create_unique_constraint(op.f("uq_users_id"), "users", ["id"])
    op.drop_column("users", "password")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("password", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(op.f("uq_users_id"), "users", type_="unique")
    op.drop_column("users", "password_hash")
    op.drop_table("analysis_results")
    op.drop_index(
        op.f("ix_separated_sources_parent_audio_id"), table_name="separated_sources"
    )
    op.drop_table("separated_sources")
    op.drop_table("logs")
    op.drop_index(op.f("ix_audio_features_audio_id"), table_name="audio_features")
    op.drop_table("audio_features")
    op.drop_index(op.f("ix_analysis_jobs_user_id"), table_name="analysis_jobs")
    op.drop_index(op.f("ix_analysis_jobs_audio_id"), table_name="analysis_jobs")
    op.drop_table("analysis_jobs")
    op.drop_index(op.f("ix_projects_user_id"), table_name="projects")
    op.drop_table("projects")
    op.drop_index(op.f("ix_audio_files_user_id"), table_name="audio_files")
    op.drop_table("audio_files")
    op.drop_table("models")
    # ### end Alembic commands ###
