"""initial schema

Revision ID: f7e406039d4d
Revises: 
Create Date: 2026-02-04 14:40:33.592316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7e406039d4d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('models',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Enum('EMOTION', 'INSTRUMENT', 'FEATURES', 'SEPARATION', name='analysistype'), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('checkpoint_path', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_models')),
    sa.UniqueConstraint('id', name=op.f('uq_models_id'))
    )
    op.create_table('users',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('id', name=op.f('uq_users_id')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('logs',
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.Enum('audio_file', 'analysis_record', 'project', name='entitytype'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('log_level', sa.Enum('info', 'warning', 'error', 'debug', name='loglevel'), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_logs__users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_logs')),
    sa.UniqueConstraint('id', name=op.f('uq_logs_id'))
    )
    op.create_index(op.f('ix_logs_entity_id'), 'logs', ['entity_id'], unique=False)
    op.create_index('ix_logs_entity_ref', 'logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_logs_user_id'), 'logs', ['user_id'], unique=False)
    op.create_table('otps',
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('purpose', sa.Enum('EMAIL_VERIFICATION', 'PASSWORD_RESET', 'TWO_FACTOR_AUTH', name='otptype'), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_otps__users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_otps')),
    sa.UniqueConstraint('id', name=op.f('uq_otps_id'))
    )
    op.create_index(op.f('ix_otps_user_id'), 'otps', ['user_id'], unique=False)
    op.create_table('projects',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_projects__users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects')),
    sa.UniqueConstraint('id', name=op.f('uq_projects_id'))
    )
    op.create_index(op.f('ix_projects_user_id'), 'projects', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('token', sa.TEXT(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens__users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('id', name=op.f('uq_refresh_tokens_id'))
    )
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('audio_files',
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_name', sa.String(length=256), nullable=False),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('sample_rate', sa.Integer(), nullable=True),
    sa.Column('channels', sa.Integer(), nullable=False),
    sa.Column('format', sa.Enum('WAV', 'MP3', 'FLAC', 'AAC', 'OGG', name='audioformat'), nullable=False),
    sa.Column('checksum', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('UPLOADED', 'PROCESSING', 'PROCESSED', 'FAILED', name='audiofilestatus'), nullable=False),
    sa.Column('source_type', sa.Enum('ORIGINAL', 'SEPARATED', name='audiosourcetype'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_audio_files__projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audio_files__users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audio_files')),
    sa.UniqueConstraint('checksum', name=op.f('uq_audio_files_checksum')),
    sa.UniqueConstraint('id', name=op.f('uq_audio_files_id'))
    )
    op.create_index(op.f('ix_audio_files_project_id'), 'audio_files', ['project_id'], unique=False)
    op.create_index(op.f('ix_audio_files_user_id'), 'audio_files', ['user_id'], unique=False)
    op.create_table('analysis_records',
    sa.Column('analysis_type', sa.Enum('EMOTION', 'INSTRUMENT', 'FEATURES', 'SEPARATION', name='analysistype'), nullable=False),
    sa.Column('results', sa.JSON(), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('model_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('audio_file_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['audio_file_id'], ['audio_files.id'], name=op.f('fk_analysis_records__audio_files'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], name=op.f('fk_analysis_records__models'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_analysis_records__projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_analysis_records__users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analysis_records')),
    sa.UniqueConstraint('id', name=op.f('uq_analysis_records_id'))
    )
    op.create_index(op.f('ix_analysis_records_audio_file_id'), 'analysis_records', ['audio_file_id'], unique=False)
    op.create_index(op.f('ix_analysis_records_project_id'), 'analysis_records', ['project_id'], unique=False)
    op.create_index(op.f('ix_analysis_records_user_id'), 'analysis_records', ['user_id'], unique=False)
    op.create_table('separated_audio_files',
    sa.Column('parent_audio_id', sa.UUID(), nullable=False),
    sa.Column('source_label', sa.Enum('VOCALS', 'DRUMS', 'BASS', 'OTHER', name='separatedsourcelabel'), nullable=False),
    sa.ForeignKeyConstraint(['parent_audio_id'], ['audio_files.id'], name=op.f('fk_separated_audio_files__audio_files'), ondelete='SET NULL')
    )
    op.create_index(op.f('ix_separated_audio_files_parent_audio_id'), 'separated_audio_files', ['parent_audio_id'], unique=False)
    op.create_table('emotion_analysis_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vgg_embeddings', sa.JSON(), nullable=True),
    sa.Column('prediction_result', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['analysis_records.id'], name=op.f('fk_emotion_analysis_records__analysis_records')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_emotion_analysis_records'))
    )
    op.create_table('feature_analysis_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('feature_vector', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['analysis_records.id'], name=op.f('fk_feature_analysis_records__analysis_records')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feature_analysis_records'))
    )
    op.create_table('instrument_analysis_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('instruments', sa.JSON(), nullable=False),
    sa.Column('confidence_scores', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['analysis_records.id'], name=op.f('fk_instrument_analysis_records__analysis_records')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_instrument_analysis_records'))
    )
    op.create_table('separation_analysis_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['analysis_records.id'], name=op.f('fk_separation_analysis_records__analysis_records')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_separation_analysis_records'))
    )
    op.create_table('audio_features',
    sa.Column('FeatureAnalysisRecord', sa.UUID(), nullable=False),
    sa.Column('feature_type', sa.Enum('LOW_LEVEL', 'MID_LEVEL', 'HIGH_LEVEL', 'EMBEDDINGS', 'MEL_SPECTROGRAM', name='featuretype'), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('audio_file_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['FeatureAnalysisRecord'], ['feature_analysis_records.id'], name=op.f('fk_audio_features__feature_analysis_records'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['audio_file_id'], ['audio_files.id'], name=op.f('fk_audio_features__audio_files'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audio_features')),
    sa.UniqueConstraint('id', name=op.f('uq_audio_features_id'))
    )
    op.create_index(op.f('ix_audio_features_FeatureAnalysisRecord'), 'audio_features', ['FeatureAnalysisRecord'], unique=False)
    op.create_index(op.f('ix_audio_features_audio_file_id'), 'audio_features', ['audio_file_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audio_features_audio_file_id'), table_name='audio_features')
    op.drop_index(op.f('ix_audio_features_FeatureAnalysisRecord'), table_name='audio_features')
    op.drop_table('audio_features')
    op.drop_table('separation_analysis_records')
    op.drop_table('instrument_analysis_records')
    op.drop_table('feature_analysis_records')
    op.drop_table('emotion_analysis_records')
    op.drop_index(op.f('ix_separated_audio_files_parent_audio_id'), table_name='separated_audio_files')
    op.drop_table('separated_audio_files')
    op.drop_index(op.f('ix_analysis_records_user_id'), table_name='analysis_records')
    op.drop_index(op.f('ix_analysis_records_project_id'), table_name='analysis_records')
    op.drop_index(op.f('ix_analysis_records_audio_file_id'), table_name='analysis_records')
    op.drop_table('analysis_records')
    op.drop_index(op.f('ix_audio_files_user_id'), table_name='audio_files')
    op.drop_index(op.f('ix_audio_files_project_id'), table_name='audio_files')
    op.drop_table('audio_files')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_projects_user_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_otps_user_id'), table_name='otps')
    op.drop_table('otps')
    op.drop_index(op.f('ix_logs_user_id'), table_name='logs')
    op.drop_index('ix_logs_entity_ref', table_name='logs')
    op.drop_index(op.f('ix_logs_entity_id'), table_name='logs')
    op.drop_table('logs')
    op.drop_table('users')
    op.drop_table('models')
    # ### end Alembic commands ###
